# Generated by Django 3.0.4 on 2020-04-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0003_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
